name: tabicl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=py39h06a4308_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cachecontrol=0.12.11=py39h06a4308_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.16.0=py39h5eee18b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cleo=2.1.0=py39h06a4308_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_0
  - crashtest=0.4.1=py39h06a4308_0
  - cryptography=42.0.5=py39hdda0065_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distlib=0.3.8=py39h06a4308_0
  - dulwich=0.21.3=py39h5eee18b_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - featuretools=1.31.0=pyhd8ed1ab_0
  - filelock=3.13.1=py39h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - holidays=0.79=pyhe01879c_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - joblib=1.4.2=py39h06a4308_0
  - jsonschema=4.19.2=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - keyring=23.13.1=py39h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - lockfile=0.12.2=py39h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - more-itertools=10.1.0=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=24.1=py39h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py39h06a4308_0
  - pkginfo=1.10.0=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - poetry=1.4.0=py39h06a4308_0
  - poetry-core=1.5.1=py39h06a4308_0
  - poetry-plugin-export=1.3.0=py39h4849bfd_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py39hd3abc70_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=24.0.0=py39h06a4308_0
  - pyproject_hooks=1.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python-build=0.10.0=py39h06a4308_0
  - python-installer=0.6.0=py39h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - rapidfuzz=3.5.2=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.3=py39h06a4308_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - rpds-py=0.10.6=py39hb02cf49_0
  - scipy=1.13.1=py39haf93ffa_0
  - secretstorage=3.3.1=py39h06a4308_1
  - setuptools=69.5.1=py39h06a4308_0
  - shellingham=1.5.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - tornado=6.4.1=py39hd3abc70_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trove-classifiers=2023.10.18=py39h06a4308_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=1.26.19=py39h06a4308_0
  - virtualenv=20.17.1=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.43.0=py39h06a4308_0
  - woodwork=0.31.0=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - alembic==1.15.2
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - beautifulsoup4==4.14.2
      - bm25s==0.2.6
      - catboost==1.2.7
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.3.0
      - coverage==7.6.1
      - cycler==0.12.1
      - dask==2024.8.0
      - dask-expr==1.1.10
      - distributed==2024.8.0
      - duckdb==1.0.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - fonttools==4.55.3
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gdown==5.2.0
      - gensim==3.8.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.0.3
      - grpcio==1.67.1
      - hdbscan==0.8.40
      - huggingface-hub==0.26.2
      - inflect==6.0.0
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - keybert==0.8.5
      - kiwisolver==1.4.7
      - lightgbm==3.3.5
      - llvmlite==0.43.0
      - locket==1.0.0
      - mako==1.3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - milvus-lite==2.4.11
      - mpmath==1.3.0
      - multidict==6.0.5
      - mysql-connector-python==9.0.0
      - narwhals==1.34.1
      - networkx==3.2.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - optuna==4.2.1
      - pandas==2.2.2
      - partd==1.4.2
      - pillow==10.2.0
      - plotly==6.0.1
      - pluggy==1.5.0
      - pooch==1.8.2
      - protobuf==6.30.0
      - pyarrow==17.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyfiglet==1.0.4
      - pyg-lib==0.4.0+pt21cu118
      - pymilvus==2.5.4
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pytest==8.3.2
      - pytest-cov==5.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-graphviz==0.20.3
      - pytorch-frame==0.2.3
      - pytz==2024.1
      - rank-bm25==0.2.2
      - regex==2024.11.6
      - relbench==1.1.0
      - rich==13.9.4
      - safetensors==0.4.5
      - scikit-learn==1.6.1
      - sentence-transformers==3.3.1
      - sentry-sdk==2.42.1
      - smart-open==7.1.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sqlalchemy==2.0.0
      - sympy==1.14.0
      - tabicl==0.1.3
      - tblib==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - toolz==1.0.0
      - torch==2.2.0+cu121
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchaudio==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - transformers==4.46.3
      - triton==2.2.0
      - tzdata==2024.1
      - ujson==5.10.0
      - umap-learn==0.5.7
      - unidecode==1.3.6
      - wandb==0.22.2
      - wordninja==2.0.0
      - wrapt==1.17.2
      - xgboost==2.1.4
      - yarl==1.9.4
      - zict==3.0.0
prefix: /home/lingze/anaconda3/envs/tabicl
